apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ekjaer/frontend:latest
        ports:
        - containerPort: 8080
        env:
          - name: BACKEND_DNS
            value: backend-svc
          - name: BACKEND_PORT
            value: '9000'

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort