# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build frontend
      run: go build -v ./frontend

    - name: Build backend
      run: go build -v ./backend

    - name: Upload code
      uses: actions/upload-artifact@v4
      with:
        name: code
        path: .
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download code
      uses: actions/download-artifact@v5
      with:
        name: code
        path: .
    - name: Test frontend
      run: go test -v ./frontend
